### PR TITLE
Update InfoPage and Bug Fixes

### LINKED ISSUE #226: [PE-D] Wrong success message when changing month
The success message is not updated when switching months

How to reproduce? 
1. Type `year 2020`
2. Type `month 10`
3. Type `month 2`

Success Message still shows "Viewing month october..."

Screenshot 2020-10-30 at 5.02.53 PM.png

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kimberlyohq/ped#8

### LINKED ISSUE #227: [PE-D] No error message for invalid dates for month Feb
There are no error messages shown when keying in invalid date for month of February and there is no response from the app due to assertion error.

How to reproduce? 
1. Type `year 2020`
2. Type `month 2`
3. Type `day 10`
4. Type `day 31`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kimberlyohq/ped#9

### LINKED ISSUE #244: [PE-D] Error message for deletepatient 0 does not match the behaviour
When I typed in deletepatient 0, the error message is "Invalid command format" as shown in the screenshot below. I think this is an invalid index error (similar to when I type in an out-of-bounds index) instead of invalid command format.

[image.png](https://raw.githubusercontent.com/lettuceman4/ped/main/files/f8b35ce5-6a1e-4390-b6a5-e2972241cdbd.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lettuceman4/ped#5

### PR DESCRIPTION
**Pull request by jianhandev**
- Fix several Calendar-related bugs (occurs when switching between days and months)
- Correct command result response messages
- Update SampleDataUtil
- Update InfoPage to show all available commands

Closes #226
Closes #227 
Closes #244  

IMAGE 2020-11-05 23:55:33

### CODE REVIEW

File: src/test/java/team/baymax/logic/parser/patient/DeletePatientCommandParserTest.java [hunk 1]
```diff
@@ -27,7 +27,6 @@ public void parse_validArgs_returnsDeleteCommand() {
 
     @Test
     public void parse_invalidArgs_throwsParseException() {
-        assertParseFailure(parser, "a", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
-                DeletePatientCommand.MESSAGE_USAGE));
+        assertParseFailure(parser, "a", MESSAGE_INVALID_INDEX);
```
Comment (thutahw) [inline src/test/java/team/baymax/logic/parser/patient/DeletePatientCommandParserTest.java:30]: If you pass in a `String`, it should be invalid command format? But i think it's ok here.

**Review by thutahw — APPROVED** [review]
LGTM
